# Default values for strimzi-kafka-operator.

watchNamespaces: []

image:
  repository: strimzi
  name: operator
  tag: 0.12.2
  imagePullPolicy: IfNotPresent
logLevel: INFO
fullReconciliationIntervalMs: 120000
operationTimeoutMs: 300000
# Docker images that operator uses to provision various components of Strimzi.  To use your own registry prefix the
# repository name with your registry URL.
# Ex) repository: registry.xyzcorp.com/strimzi/zookeeper
zookeeper:
  image:
    repository: strimzi
    name: kafka
    tagPrefix: 0.12.2
kafka:
  image:
    repository: strimzi
    name: kafka
    tagPrefix: 0.12.2
kafkaConnect:
  image:
    repository: strimzi
    name: kafka
    tagPrefix: 0.12.2
kafkaConnects2i:
  image:
    repository: strimzi
    name: kafka
    tagPrefix: 0.12.2
topicOperator:
  image:
    repository: strimzi
    name: operator
    tag: 0.12.2
userOperator:
  image:
    repository: strimzi
    name: operator
    tag: 0.12.2
kafkaInit:
  image:
    repository: strimzi
    name: operator
    tag: 0.12.2
tlsSidecarZookeeper:
  image:
    repository: strimzi
    name: kafka
    tagPrefix: 0.12.2
tlsSidecarKafka:
  image:
    repository: strimzi
    name: kafka
    tagPrefix: 0.12.2
tlsSidecarEntityOperator:
  image:
    repository: strimzi
    name: kafka
    tagPrefix: 0.12.2
kafkaMirrorMaker:
  image:
    repository: strimzi
    name: kafka
    tagPrefix: 0.12.2
kafkaBridge:
  image:
    repository: strimzi
    name: kafka-bridge
    tag: 0.12.2
resources:
  limits:
    memory: 256Mi
    cpu: 1000m
  requests:
    memory: 256Mi
    cpu: 200m
livenessProbe:
  initialDelaySeconds: 10
  periodSeconds: 30
readinessProbe:
  initialDelaySeconds: 10
  periodSeconds: 30

# Override the docker image repository used by all Strimzi images
# imageRepositoryOverride: foobar
# Override the docker image tag used by all Strimzi images
# imageTagOverride: latest
createGlobalResources: true
