apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kafka-cluster
  namespace: kafka
spec:
  releaseName: kafka-cluster
  chart:
    git: ssh://git@github.com:John-Athan/flux-get-started.git
    ref: master
    path: charts/kafka-cluster
  values:
    kafka:
      version: 2.2.1
      replicaCount: 3
      resources:
        requests:
          cpu: "1000m"
          memory: 2Gi
      storage:
        size: "7Gi"
      config:
        offsets.topic.replication.factor: 3
        transaction.state.log.replication.factor: 3
        transaction.state.log.min.isr: 2
        transaction.max.timeout.ms: 1800000
        unclean.leader.election.enable: true
        default.replication.factor: 3
        log.message.format.version: "2.2"
        log.message.timestamp.type: "LogAppendTime"
        log.retention.hours: 96
        log.segment.bytes: "1073741824"
        log.retention.check.interval.ms: 300000
        auto.create.topics.enable: false
        replica.fetch.max.bytes: "67108864" # 64MB