apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: second-strimzi
  namespace: second-strimzi-operator
spec:
  releaseName: second-strimzi
  chart:
    git: https://github.com/John-Athan/flux-get-started.git
    ref: master
    path: charts/strimzi-kafka-operator
  values:
    watchNamespaces:
      - second-kafka
    createGlobalResources: false