apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaMirrorMaker
metadata:
  annotations:
    helm.fluxcd.io/antecedent: distributed-tracing:helmrelease/zipkin-bi-test-mirror
  labels:
    app.kubernetes.io/instance: zipkin-bi-test-mirror
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: bi-test-kafka
    helm.sh/chart: bi-kafka-strimzi-mirror-maker-1.0.3
  name: bi-test-kafka
  namespace: second-kafka
spec:
  consumer:
    bootstrapServers: http://strimzi-kafka-cluster-kafka-bootstrap.bi-test-kafka:9092
    groupId: zipkin-test-mirror-maker
  jvmOptions:
    -XX:
      ExitOnOutOfMemoryError: true
      PrintCommandLineFlags: true
      PrintFlagsFinal: true
      UseG1GC: true
    gcLoggingEnabled: false
  logging:
    loggers:
      logger.name: INFO
    type: inline
  producer:
    bootstrapServers: http://strimzi-kafka-cluster-kafka-bootstrap.distributed-tracing:9092
  replicas: 1
  template:
    mirrorMakerContainer:
      env:
        - name: DYNAMIC_HEAP_FRACTION
          value: "0.8"
  version: 2.5.0
  whitelist: zipkin
