---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: strimzi
  namespace: strimzi-operator
spec:
  releaseName: strimzi
  chart:
    repository: https://strimzi.io/charts/
    name: strimzi-kafka-operator
    version: 0.18.0
  values:
    watchNamespaces:
      - kafka
    logLevel: INFO
    createGlobalResources: false
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: second-strimzi
  namespace: second-strimzi-operator
spec:
  releaseName: second-strimzi
  chart:
    repository: https://strimzi.io/charts/
    name: strimzi-kafka-operator
    version: 0.15.0
  values:
    watchNamespaces:
      - second-kafka
    logLevel: INFO
    createGlobalResources: false
---