---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: strimzi
  namespace: strimzi-operator
spec:
  releaseName: strimzi
  chart:
    git: https://github.com/John-Athan/flux-get-started.git
    ref: master
    path: charts/strimzi-kafka-operator-12
  values:
    watchNamespaces:
      - kafka
      - second-kafka
    logLevel: INFO
---
