apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: strimzi
  namespace: strimzi-operator
spec:
  releaseName: strimzi
  chart:
    repository: https://strimzi.io/charts/
    name: strimzi-kafka-operator
    version: 0.12.0
  values:
    watchNamespaces:
      - kafka
